In [1]:
import numpy as np

In [3]:
A=np.array([[-2,2,-1,0,1],[2,3,1,2,2],[3,-3,2,4,3],[-2,1,-2,-1,0]])
print(A)

[[-2  2 -1  0  1]
 [ 2  3  1  2  2]
 [ 3 -3  2  4  3]
 [-2  1 -2 -1  0]]


In [5]:
A.min(axis=1)

array([-2,  1, -3, -2])

In [6]:
max(A.min(axis=1))

1

In [7]:
min(A.max(axis=0))

2

In [8]:
P=np.array([0.1,0.2,0.2,0.5])
Q=np.array([0.3,0.3,0,0.1,0.3])
print(P,Q)

[0.1 0.2 0.2 0.5] [0.3 0.3 0.  0.1 0.3]


In [9]:
P.T@A@Q

0.55