In [1]:
import numpy as np
from scipy.optimize import linprog

In [2]:
A=np.array([[2,3,1],[1,2,3], [3,1,2]])
print(A)

[[2 3 1]
 [1 2 3]
 [3 1 2]]


In [3]:
#Первый
c=np.array([-1,-1,-1])
b=np.array([1,1,1])
x_bounds=[(0,None),(0,None),(0,None)]

res=linprog(c,A_ub=A.T,b_ub=b,bounds=x_bounds)

res

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -0.5
              x: [ 1.667e-01  1.667e-01  1.667e-01]
            nit: 3
          lower:  residual: [ 1.667e-01  1.667e-01  1.667e-01]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  0.000e+00  0.000e+00]
                 marginals: [-1.667e-01 -1.667e-01 -1.667e-01]
 mip_node_count: 0
 mip_dual_bound: 0.0
        mip_gap: 0.0

In [4]:
res.x

array([0.16666667, 0.16666667, 0.16666667])

In [5]:
res.fun

-0.5

In [6]:
print('цена игры=', -1/res.fun-2)
print('равновесная стратегия:', -res.x/res.fun)

цена игры= 0.0
равновесная стратегия: [0.33333333 0.33333333 0.33333333]


In [7]:
#Второй
c=np.array([1,1,1])
b=np.array([-1,-1,-1])
x_bounds=[(0,None),(0,None),(0,None)]

res=linprog(c,A_ub=-A,b_ub=b,bounds=x_bounds)
res

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 0.5
              x: [ 1.667e-01  1.667e-01  1.667e-01]
            nit: 3
          lower:  residual: [ 1.667e-01  1.667e-01  1.667e-01]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  0.000e+00  0.000e+00]
                 marginals: [-1.667e-01 -1.667e-01 -1.667e-01]
 mip_node_count: 0
 mip_dual_bound: 0.0
        mip_gap: 0.0

In [8]:
print('цена игры=', 1/res.fun-2)
print('равновесная стратегия:', res.x/res.fun)

цена игры= 0.0
равновесная стратегия: [0.33333333 0.33333333 0.33333333]
